[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.28"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
always_use_create_2_factory = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
